name: Build Android apk from Web code

on:
  push:
    branches: [ "apk" ]
  pull_request:
    branches: [ "apk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: gradle
    - name: Create the Android project
      run: npx cap add android
    - name: Bump version number
      run: npm run bump
    - name: Build apk
      run: npm run build-apk
